### ISSUE TITLE
Allow validator to validate only against Core Specification

### ISSUE THREAD

**Issue by GitGuruGangsta** [FirelyTeam/firely-validator-api#145]
**Is your feature request related to a problem? Please describe.**

The Validate-Extension (Hl7.Fhir.Model on Base) on Resource doesn't  give a proper validation message.
Only an exception is thrown on the first invalid field. If there are more invalidities you won't know.

The Validator (from Hl7.Fhir.Validation in Hl7.Fhir.Specification.R4 package) has no settings to only validate against the core specifications.
Profiles are checked always. It would be helpful to have a setting not to follow profiles or do a validation ONLY against the core specification.

The Validator has the better Outcome-Messaging, but it is also not very helpful that it gives errors, when extension urls cannot be resolved, which is already adressed in [#2105 ]

**Describe the solution you'd like**
Possibilty to use the Validator against core specifications ONLY

**Describe alternatives you've considered**

Better and full outcome messaging of  "validate"-extension-method on Resource

**Comment by mmsmits** [comment]
This is possible by now
