### ISSUE TITLE
Improvement for validation of StructureDefinition.id

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/firely-validator-api#158]
**Is your feature request related to a problem? Please describe.**
In R4 the type of StructureDefinition.id is mistakingly set to "string" in the structuredefinition-fhir-type extension. See https://www.hl7.org/fhir/structuredefinition.profile.json.html. Therefore no validation of the id datatype is happening when running the validator. This lets to easy to make mistakes, like including an "_" in it.

**Describe the solution you'd like**
To avoid tooling issues when consuming StructureDefinitions with invalid ids, it would be good to manually fix this issue in the appropriate places in the SDK and apply the id regex.

**Additional context**
The issue in the specification has been fixed in R5.
Unit test to reproduce the issue can be found in fix/validation-id-structuredefinition (TestInvalidStructureDefinitionIdIsRejected in BasicValidationTests.cs)

**Comment by mmsmits** [comment]
This should be fixed by now, right?
