### ISSUE TITLE
Profile validation (on id/regex) not working

### ISSUE THREAD

**Issue by andygemis** [FirelyTeam/firely-validator-api#159]
Currently porting some code from 
  .net framework 4.8 STU3 (using package Hl7.Fhir.STU3 v0.94.0) 
to 
  .net core 3.1 using package Hl7.Fhir.R4 v 3.4.0

Under STU3 - works :-
 
```

      var patient = new Patient();
			patient.Id = string.Empty.PadLeft(90, '!');

			var validator = new Validator(new ValidationSettings()
			{
				ResourceResolver = new ZipSource(@"Packages\Hl7.Fhir.Specification.STU3.0.94.0\contentFiles\any\any\specification.zip"),
			});

var validationResut =validator.Validate(new PocoNavigator(patient));

```
STU3 Patient INPUT 
`{"resourceType":"Patient","id":"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"}`

STU3 OperationOutcome/validation result
`{"resourceType":"OperationOutcome","issue":[{"severity":"error","code":"invalid","details":{"coding":[{"system":"http://hl7.org/fhir/dotnet-api-operation-outcome","code":"1006"}],"text":"Primitive value '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!' does not match regex '[A-Za-z0-9\\-\\.]{1,64}'"},"location":["Patient.id[0]"]}]}
`

Under R4

```
var patient = new Patient();
            patient.Id = string.Empty.PadLeft(90, '!');


            var validator = new Validator(new ValidationSettings()
            {
                ResourceResolver = new ZipSource(@"/workspaces/tst/bin/Debug/netcoreapp3.1/specification.zip"),
                ResolveExternalReferences = false
            });

            var validationResut = validator.Validate(patient.ToTypedElement());

```
R4 Patient INPUT 
"{\"resourceType\":\"Patient\",\"id\":\"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\"}"

R4 OperationOutcome/validation result
"{\"resourceType\":\"OperationOutcome\"}"

Ie the regex/length isn''t been caught,

But other tests for missing manditory elements are being trapped - seems to be regex based?

**Comment by mmsmits** [comment]
This should be fixed by now
