### ISSUE TITLE
Validation: allow warning on unknown extensions

### ISSUE THREAD

**Issue by cknaap** [FirelyTeam/firely-validator-api#169]
Situation: Validate a resource with an extension whose definition cannot be retrieved in the current context of validation.
Current behaviour: the validator will report an error on the missing extension and return 'error' as the validation result.
Requested behaviour: 
- Create a ValidatorSetting that allows for reporting this as a warning instead.
- If the setting is set to 'warning': return success as the validation result, with a warning in the OO stating that which definition could not be retrieved (so the same message as currently, but with level 'warning').

**Comment by mmsmits** [comment]
This has already been fixed:
See `UnresolvableExtensionAreJustWarnings()` for the unit test
