### ISSUE TITLE
Implement/improve validation of StructureDefinition resources

### ISSUE THREAD

**Issue by wmrutten** [FirelyTeam/firely-validator-api#173]
The validator implementation has been focused on validating a Resource instance against a profile.
However a profile is also a resource instance that can be validated against it's base profile c.q. StructureDefinition and ElementDefinition. A validator should then report all constraints that are invalid according to FHIR rules (e.g. relaxing instead of constraining).
Note: Simplifier already demonstrates that the validator is capable of validating StructureDefinitions, using the standard validation logic. However we can probably improve the quality and completeness of the report by implementing custom warnings specifically targeting StructureDefinition. This ticket is intended as a reminder.

**Comment by mmsmits** [comment]
We are actually doing this now in the enterprise validation.
