### ISSUE TITLE
Investigate: validation does not pick up on slice cardinality?

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-validator-api#215]
When running the demo, using the supplied bundle example, the constraints should ensure that the vital signs section appears exactly once (this is done using slicing). However, when I duplicate that section, validation succeeds. I have to dive into why this is, probably by putting this example as an integration test in the validator tests (it is part of the legacy validator tests).

**Comment by mmsmits** [comment]
Use the validation demo to test the Vital Signs bundle

**Comment by ewoutkramer** [comment]
I used this example in my demo last Friday, this works perfectly well.
