### ISSUE TITLE
New Validator Requires .NET 8

### ISSUE THREAD

**Issue by Narnian12** [FirelyTeam/firely-validator-api#255]
When trying to install and run the new validator on our .NET 6 project, we are running into the following error:

**NU1202: Package Firely.Fhir.Validation.R4 2.0.0 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package Firely.Fhir.Validation.R4 2.0.0 supports: net8.0 (.NETCoreApp,Version=v8.0)**

We definitely have plans to update to .NET 8, but it looks to still have the "Early Access" flag (at least in the Azure Portal), so we are not upgrading just yet.

Are there plans to allow this validator to work in older .NET versions?

**Comment by ewoutkramer** [comment]
We planned to ship .NET 8 + netstandard2.1 in line with our policy to support both the newest + "anything that supports netstandard), but we didn't actually ship netstandard2.1.  Working on it.

**Comment by ewoutkramer** [comment]
By the way, in the meantime, you can simply change the target framework to net6.0 and recompile the project yourself, I just checked it, it compiles without any problems under net6.0.

**Comment by Narnian12** [comment]
Sounds good, thank you so much!

**Comment by mmsmits** [comment]
Just released version 2.0.1 support netstandard2.1, so this should build now on in a NET6 project

**Comment by Narnian12** [comment]
Perfect, thank you!
