### ISSUE TITLE
New Firely validator does not complain when extension is used outside of its context

### ISSUE THREAD

**Issue by wardweistra** [FirelyTeam/firely-validator-api#267]
**Describe the bug**
When validating a resource which uses an extension outside of its defined context, the new Firely validator does not report an error.

**To Reproduce**
1. Take an extension which has context defined as the element `Address`: <https://simplifier.net/Signal-MSO-FHIR-Profiles/SignalRegion/~xml>
2. Take a Location resource where an extension is used in the root: <https://simplifier.net/snippet/wardweistra/66>
3. Validate it with the new validator, eg with the Validation Demo tool
4. See that it reports SUCCESS without any errors or warnings

**Expected behavior**
Error that the extension is incorrectly used

**Screenshots**
See next comment

**Version used:**
 - FHIR Version: R4
 - Version: This commit of the validation demo: https://github.com/FirelyTeam/Firely.Fhir.ValidationDemo/commit/a3a7051ec967310cef2474b66a88369d3003f027

**Additional context**
[Slack Message](https://firelyteam.slack.com/archives/C011XD1TKL0/p1702898118334729?thread_ts=1702898118.334729&cid=C011XD1TKL0)

**Comment by mmsmits** [comment]
The new validator is available, I transferred the issue

**Comment by ewoutkramer** [comment]
> No, extension context checking was never implemented in the old validator.

Just to manage expectations: It's not yet implemented in the new one either ;-)

**Comment by mmsmits** [comment]
duplicate of #134

**Comment by mmsmits** [comment]
The context can be defined in three different ways:
http://hl7.org/fhir/valueset-extension-context-type.html

We have notion of the definition path to validate these contexts.
