### ISSUE TITLE
Profiles can only constrain `defaultValue[x]` in logical models

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-validator-api#268]
From the FHIR-I call:

FHIR-42619: Discussion about handling default values in logical models using FSH. Grahame will check if the Java validator reject profiles with ElementDefinition.defaultValue[x] in it. Apparently it’s only allowed as part of logical models, not within a profile. We might want to do the same @Ewout

**Comment by mmsmits** [comment]
Closed, this is already a contraint in the FHIR spec (sdf-21), and we already support those.
