### ISSUE TITLE
Add support for using repeating elements as a discriminator in a (pattern) slicing

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/firely-validator-api#270]
**Is your feature request related to a problem? Please describe.**
I'm trying to define a profile on Observation that contains a slice on Observation.component. The element is sliced by pattern on Observation.component.code.coding. At least on coding defined by the pattern on the discriminator must be present. However, when having multiple codings on the discriminator in the actual instance (additional optional codings, not defined in the pattern), the validator throws an exception:

{Code="Exception" Details.Text="Internal logic failure: The instance has multiple elements at 'Observation.component[0]' for the discriminator path 'code.coding'. Don't know how to handle that."}

**Describe the solution you'd like**
* If a pattern is defined on the element, match the slice if at least the element from the pattern is present, additional codings allowed.
* If a fixedValue is defined on the element, match the slice if only and only if that element is present

**Comment by ewoutkramer** [comment]
Happy to report that this is supported in the new validator. For those interested, this construct will result in the following elementschema:

```
 "case": [
          {
            "name": "test",
            "condition": {
              "pathSelector": {
                "path": "code.coding",
                "assertion": {
                  "pattern[Coding]": {
                    "system": "http://example.org/fhir/CodeSystem/test",
                    "code": "test"
                  }
                }
              }
            },
```

We can see here that `code.coding` is selected from the instance and then matched against the `pattern[Coding]` rule, which does what its name says, and will match the value against the given pattern, resulting in the behaviour Alexander is looking for.
