### ISSUE TITLE
FhirPath's isDistinct doesn't always work 

### ISSUE THREAD

**Issue by luisgmgouveia** [FirelyTeam/firely-validator-api#294]
Hi,

This week our team replaced the R5 legacy validator by this new one released this year (v2.1.0). We had some hope the new one would solve an issue we had on FhirPaths. Unfortunately it didn't.

The problem is that, while this FhirPath expression (applied on PackagedProductDefinition.legalStatusOfSupply) works:

**_- jurisdiction.extension.where(url = 'http://ema.europa.eu/fhir/extension/countryLegalStatusOfSupply').isDistinct()_**

This one is ignored:

**_- jurisdiction.extension.where(url = 'http://ema.europa.eu/fhir/extension/countryLegalStatusOfSupply').valueCodeableConcept.coding.code.isDistinct()_**

That means we are able to make sure that the entire extension does not repeat, but we can't make sure that the code doesn't repeat.

In the java validator [(validator_cli.jar)](https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar) both work fine. On the Firely validator, only the first one works.

Thanks a lot!

**Comment by mmsmits** [comment]
` jurisdiction.extension.where(url = 'http://ema.europa.eu/fhir/extension/countryLegalStatusOfSupply').valueCodeableConcept.coding.code.isDistinct()`

seems incorrect, it should be

` jurisdiction.extension.where(url = 'http://ema.europa.eu/fhir/extension/countryLegalStatusOfSupply').value.ofType(CodeableConcept).coding.code.isDistinct()`
