### ISSUE TITLE
Seemingly incorrect error thrown in the new validator. 

### ISSUE THREAD

**Issue by MatthijsvdWielen** [FirelyTeam/firely-validator-api#298]
Validating the following example gives the error below. Although the profile looks correct. 
See attached example and base profile. 

There is a reproduction project on our staging environment: https://staging.simplifier.net/bellucciengenir/hc40-orderentry.observation

Overall result: FAILURE
[WARNING] Cannot resolve reference ServiceRequest/IHUB.1-284679-202209051330-10-0.65045 (at Observation.basedOn[0], element Observation(https://eng.it/fhir/StructureDefinition/Observation_Eng).basedOn)
[WARNING] Cannot resolve reference Patient/1 (at Observation.subject[0], element Observation(https://eng.it/fhir/StructureDefinition/Observation_Eng).subject)
[WARNING] Cannot resolve reference Encounter/HC40-ER.b829db56-8a2f-4c6b-9949-38c4de0664e0 (at Observation.encounter[0], element Observation(https://eng.it/fhir/StructureDefinition/Observation_Eng).encounter)
[ERROR] Encountered unknown child elements 'value','unit','system','code' (at Observation.valueQuantity[0], element Observation(https://eng.it/fhir/StructureDefinition/Observation_Eng).value[x])
[WARNING] Cannot resolve reference Specimen/IHUB.28467901 (at Observation.specimen[0], element Observation(https://eng.it/fhir/StructureDefinition/Observation_Eng).specimen)

**Comment by mmsmits** [comment]
@MatthijsvdWielen has this been tested with the new validator?

**Comment by MatthijsvdWielen** [comment]
@mmsmits yes

**Comment by mmsmits** [comment]
It's even in the title I see 🙈
