### ISSUE TITLE
Error thrown by validator for a url that need not be resolvable during validation.

### ISSUE THREAD

**Issue by MatthijsvdWielen** [FirelyTeam/firely-validator-api#383]
Following this profile: https://simplifier.net/packages/nictiz.fhir.nl.stu3.zib2017/2.2.18/files/2317003

The errors thrown when validating the attached profile against the [Nictiz nl core package.](https://simplifier.net/packages/nictiz.fhir.nl.stu3.zib2017/2.2.18) 

Profile:
[documentset.zip](https://github.com/user-attachments/files/17455643/documentset.zip)

The new validator v2.4.0 returns:
`Incomplete : Unable to resolve reference to profile 'http://hl7.org/fhir/StructureDefinition/url'
Bundle.entry[1].resource[0].content[0].attachment[0].url[0] `

 See: https://staging.simplifier.net/validator?scope=nictiz.fhir.nl.stu3.zib2017@2.1.5&version=Modern

The legacy validator throws the same error.

**Comment by mmsmits** [comment]
@MatthijsvdWielen,
This doesn't fail in a local validator. I suspect this is a bug in Simplifier's resource resolver. 
The url `http://hl7.org/fhir/StructureDefinition/url` doesn't exist and should be `http://hl7.org/fhir/StructureDefinition/uri`. But this is not something that is done by the snapshot or the validator in this case.
Maybe simplifier has magic here?

**Comment by mmsmits** [comment]
@MatthijsvdWielen never mind. Not simplifier's problem 🐵

**Comment by mmsmits** [comment]
This is a problem in the `PocoStructureDefinitionSummaryProvider`
